version: '3'
services:
  lattegan:
    build:
      context: .
    entrypoint: /bin/bash
    # command: -c "pip install -r requirements.txt && python src/main.py --yaml_path ./params/exp078.yaml --pretrain_tirg"
    command: -c "pip install -r requirements.txt && python src/main.py --yaml_path ./params/exp085.yaml --create_embs_from_model"
    # command: -c "pip install -r requirements.txt && python src/main.py --yaml_path ./params/exp169.yaml --train_propv1_scain_geneva"

    # command: -c "pip install -r requirements.txt && python src/main.py --yaml_path ./params/exp169.yaml --train_propv1_scain_geneva"

    container_name: lattegan
    privileged: true
    environment:
      - TPU_NAME=tpu_name
      - TF_CPP_MIN_LOG_LEVEL=0
      - XRT_TPU_CONFIG=localservice;0;localhost:8470
      - TF_XLA_FLAGS=--tf_xla_enable_xla_devices
    volumes:
      - ./:/lattegan
      - /var/run/docker.sock:/var/run-docker.sock
      - /usr/share/tpu/:/usr/share/tpu/
      - /lib/libtpu.so:/lib/libtpu.so
    devices:
      - "/dev/accel0:/dev/accel0"
      - "/dev/accel1:/dev/accel1"
      - "/dev/accel2:/dev/accel2"
      - "/dev/accel3:/dev/accel3"
    deploy:
      resources:
        reservations:
          cpus: '16'
          memory: '64G'
